# ENV PORT 8080
# ENV HOST "0.0.0.0"
# ENV DB_HOST "localhost"
# ENV DB_PORT "3306"
# ENV DB_USERNAME "admin"
# ENV DB_PASSWORD "AlienPassword123"
# ENV DB_NAME "mysqltst"

# REACT_APP_API_URL

images:
  api: ghcr.io/maurosala/fat-squirrels_api:latest
  app: ghcr.io/maurosala/fat-squirrels_app:latest

api:
  db:
    username: admin
    name: renomydb

appUrl: app-demo.krateo.io
apiUrl: api-demo.krateo.io
